CREATE VIEW V_WORK_ORDER AS
SELECT 
    BASE.*,
    QUEUE.QUEUENAME, --工作组
    STATUS.STATUSNAME STATUSNAME, -- 状态
    USERT.CINAME CINAME, --指派给 
    ORG.NAME ORG_NAME, --地点
    PRID.PRIORITYNAME PRIORITYNAME --优先级
FROM
(
    SELECT
        WO.WORKORDERID WORKORDERID, --请求ID
        WO.CREATEDTIME CREATED_TIME, --创建时间
        WO.DUEBYTIME DUEBY_TIME,--逾期时间
        WOS.LAST_TECH_UPDATE UPDATE_TIME,--最后更新时间
        WO.TITLE TITLE,--主题
        WO.SITEID SITE_ID, --地点 ID Y
        WOF.UDF_CHAR2 RESOURCE, -- 机型Resource
        WOF.UDF_CHAR14 TYPE,--需求类型
        WOF.UDF_DOUBLE1 DOWN_TIME,--停机时间
        WOF.UDF_CHAR23 LINKED_REQ_ID,--关联请求ID
        WOF.UDF_CHAR31 MR_STATUS,--航材处理状态
        WOF.UDF_LONG1 HOLD_TIME,--中断次数
        WOF.UDF_CHAR38 ACT_TYPE,--动作类型
        WOF.UDF_CHAR41 RETURN_MATERIAL_STATUS,--退料处理状态
        WOF.UDF_LONG3 ME_ORDER_COUNT,--Me订件数量
        WOS.PRIORITYID PRIORITY_ID, --优先级 ID Y
        WOS.OWNERID OWNER_ID, --指派给 ID Y
        WOS.STATUSID STATUS_ID, --状态 ID Y
        WOQ.QUEUEID QUEUE_ID --工作组 ID Y
    FROM 
        WorkOrder WO,
        WorkOrder_Fields WOF,
        WorkOrderStates WOS,
        WorkOrder_Queue WOQ
    WHERE WO.WORKORDERID = WOF.WORKORDERID
    AND WOS.WORKORDERID = WO.WORKORDERID
    AND WOQ.WORKORDERID = WO.WORKORDERID
)
AS BASE
LEFT JOIN SDOrganization ORG ON ORG.ORG_ID = BASE.SITE_ID
LEFT JOIN PriorityDefinition PRID ON PRID.PRIORITYID = BASE.PRIORITY_ID
LEFT JOIN (SELECT SDUser.USERID, CI.CINAME FROM SDUser, CI WHERE SDUser.CIID = CI.CIID) AS USERT ON USERT.USERID = BASE.OWNER_ID
LEFT JOIN StatusDefinition STATUS ON STATUS.STATUSID = BASE.STATUS_ID
LEFT JOIN QueueDefinition QUEUE ON QUEUE.QUEUEID = BASE.QUEUE_ID;


CREATE VIEW V_WORK_ORDER_WORK_LOG AS
SELECT
    BASE.*,
    OWNER.FIRST_NAME OWNER_FIRST_NAME, --所有者 
    OWNER.MIDDLE_NAME OWNER_MIDDLE_NAME, --所有者 
    OWNER.LAST_NAME OWNER_LAST_NAME, --所有者 
    CREATEBY.FIRST_NAME CREATEBY_FIRST_NAME, --创建人
    CREATEBY.MIDDLE_NAME CREATEBY_MIDDLE_NAME, --创建人
    CREATEBY.LAST_NAME CREATEBY_LAST_NAME --创建人
FROM
(
    SELECT 
        WOC.WORKORDERID WORKORDERID, --请求ID
        C.TECHNICIANID TECHNICIAN_ID, --所有者 ID Y
        C.CREATEDBY CREATEDBY_ID, --创建人 ID Y
        C.DESCRIPTION, --描述
        C.TIMESPENT, --解决问题所用的时间(毫秒)
        C.TS_ENDTIME, --结束时间
        CF.UDF_CHAR1, --拆下部件名称
        CF.UDF_CHAR3, --拆下部件件号 P/N
        CF.UDF_CHAR5, --拆下部件序号 S/N
        CF.UDF_LONG1, --停机时间-日志(Minutes)
        CF.UDF_CHAR2, --安装/维修部件名称
        CF.UDF_CHAR4, --安装/维修部件件号 P/N
        CF.UDF_CHAR6, --安装/维修部件序号 S/N
        CF.UDF_LONG2 --丢失时间-日志(Minutes)
    FROM
        WorkOrderToCharge WOC,
        ChargesTable C,
        WorkLog_Fields CF
    WHERE
        WOC.CHARGEID = C.CHARGEID
        AND CF.WORKLOGID = C.CHARGEID
)
AS BASE
LEFT JOIN AaaUser OWNER ON OWNER.USER_ID = BASE.TECHNICIAN_ID
LEFT JOIN AaaUser CREATEBY ON CREATEBY.USER_ID = BASE.CREATEDBY_ID;
 
